services:
  lespass_postgres:
    image: postgres:13-bookworm
    restart: always
    container_name: lespass_postgres
    hostname: lespass_postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file: .env
    networks:
      - lespass_backend


  lespass_memcached:
    image: memcached:1.6
    container_name: lespass_memcached
    hostname: lespass_memcached
    restart: always
    networks:
      - lespass_backend


  lespass_redis:
    container_name: lespass_redis
    hostname: lespass_redis
    image: redis:7.2.3-bookworm
    restart: always
    networks:
      - lespass_backend

  lespass_django:
    image: tibillet/lespass:${LESPASS_VERSION:-latest}
    restart: always
    container_name: lespass_django
    hostname: lespass_django
    volumes:
      - ./www:/DjangoFiles/www
      - ./logs:/DjangoFiles/logs
      - ./backup:/Backup
      - ./ssh:/home/tibillet/.ssh # if you want ssh borgbackup
      - ./settings.py:/DjangoFiles/TiBillet/settings.py
      - ./custom_patches/Administration/admin_tenant.py:/DjangoFiles/Administration/admin_tenant.py
      - ./custom_patches/BaseBillet/templates/emails/connexion.html:/DjangoFiles/BaseBillet/templates/emails/connexion.html
      - ./custom_patches/BaseBillet/templates/reunion/forms/login.html:/DjangoFiles/BaseBillet/templates/reunion/forms/login.html
      - ./custom_patches/BaseBillet/templates/reunion/partials/navbar.html:/DjangoFiles/BaseBillet/templates/reunion/partials/navbar.html
      - ./custom_patches/BaseBillet/views.py:/DjangoFiles/BaseBillet/views.py
      - ./custom_patches/BaseBillet/templates/reunion/views/account/preferences.html:/DjangoFiles/BaseBillet/templates/reunion/views/account/preferences.html
      - ./custom_patches/BaseBillet/templates/reunion/views/account/balance.html:/DjangoFiles/BaseBillet/templates/reunion/views/account/balance.html
      - ./custom_patches/BaseBillet/templates/reunion/views/account/card.html:/DjangoFiles/BaseBillet/templates/reunion/views/account/card.html
      - ./custom_patches/BaseBillet/templates/reunion/views/account/index.html:/DjangoFiles/BaseBillet/templates/reunion/views/account/index.html
      - ./custom_patches/BaseBillet/templates/reunion/views/home.html:/DjangoFiles/BaseBillet/templates/reunion/views/home.html
      - ./custom_patches/BaseBillet/templates/reunion/partials/account/transaction_history.html:/DjangoFiles/BaseBillet/templates/reunion/partials/account/transaction_history.html
      - ./custom_patches/ApiBillet/urls.py:/DjangoFiles/ApiBillet/urls.py
      - ./custom_patches/ApiBillet/cashless_onboarding.py:/DjangoFiles/ApiBillet/cashless_onboarding.py
      - ./custom_patches/BaseBillet/urls.py:/DjangoFiles/BaseBillet/urls.py
      - ./custom_patches/BaseBillet/templates/reunion/views/guest_refill.html:/DjangoFiles/BaseBillet/templates/reunion/views/guest_refill.html
      - ./custom_patches/BaseBillet/templates/reunion/views/guest_refill_success.html:/DjangoFiles/BaseBillet/templates/reunion/views/guest_refill_success.html
    env_file: .env
    depends_on:
      - lespass_postgres
      - lespass_redis
      - lespass_memcached
    links:
      - lespass_postgres:postgres
      - lespass_redis:redis
      - lespass_memcached:memcached
    networks:
      - lespass_backend
    # only useful for dev purpose :
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "lespass.tibillet.localhost:172.17.0.1"
      - "cashless.tibillet.localhost:172.17.0.1"

  lespass_celery:
    image: tibillet/lespass:${LESPASS_VERSION:-latest}
    restart: always
    container_name: lespass_celery
    hostname: lespass_celery
    env_file: .env
    volumes:
      - ./settings.py:/DjangoFiles/TiBillet/settings.py
      - ./custom_patches/BaseBillet/templates/emails/connexion.html:/DjangoFiles/BaseBillet/templates/emails/connexion.html
    depends_on:
      - lespass_postgres
      - lespass_redis
      - lespass_memcached
    links:
      - lespass_postgres:postgres
      - lespass_redis:redis
      - lespass_memcached:memcached
    command: "poetry run celery -A TiBillet worker -l INFO -B"
    networks:
      - lespass_backend


  lespass_nginx:
    image: nginx:latest
    container_name: lespass_nginx
    hostname: lespass_nginx
    restart: always
    links:
      - lespass_django:lespass_django
    volumes:
      - ./www:/www
      - ./logs:/logs
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.lespass.tls.certresolver=myresolver
      - traefik.http.routers.lespass.rule=Host(`$DOMAIN`)
    networks:
      - frontend
      - lespass_backend

networks:
  frontend:
    external: true
  lespass_backend:
