"""Fast QR-card onboarding, adapted from the archived 100J flow.

The QR code is public (printed on the card): it is not an authentication token
for an already linked card or an existing email account.
"""

import logging

from django.contrib import messages
from django.contrib.auth import login
from django.core import signing
from django.core.cache import cache
from django.db import connection
from django.http import Http404, HttpResponseForbidden, HttpResponseNotAllowed, HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.views.decorators.http import require_GET
from django_htmx.http import HttpResponseClientRedirect
from django_tenants.utils import tenant_context

from AuthBillet.models import TibilletUser, Wallet
from AuthBillet.utils import get_or_create_user, sender_mail_connect
from BaseBillet.models import Configuration, Membership
from BaseBillet.validators import LinkQrCodeValidator
from Customers.models import Client, Domain
from fedow_connect.fedow_api import FedowAPI

logger = logging.getLogger(__name__)


def _card(request, card_id):
    """Resolve a generic QR in its originating tenant, as ScanQrCode does."""
    tenant = connection.tenant
    if tenant.categorie != Client.SALLE_SPECTACLE:
        tenant = Client.objects.filter(categorie=Client.SALLE_SPECTACLE).first()
    if tenant is None:
        raise Http404("Carte inconnue")
    with tenant_context(tenant):
        card = FedowAPI().NFCcard.qr_retrieve(card_id)
        if not card:
            raise Http404("Carte inconnue")
        lespass_domain = card.get('origin', {}).get('place', {}).get('lespass_domain')
        domain = Domain.objects.filter(domain=lespass_domain).first()
        if domain is None or domain.tenant.get_primary_domain() is None:
            raise Http404("Origine de la carte inconnue")
        canonical = domain.tenant.get_primary_domain().domain
    return card, canonical


def _context(request, card_id=None):
    # Import lazily: views.py also imports this module through urls.py.
    from BaseBillet.views import get_context
    context = get_context(request)
    context['qrcode_uuid'] = card_id
    return context


def _send_magic_link(user, card_id):
    # Avoid triggering unlimited mail from repeated QR scans. The link itself
    # is generated by the existing mailer and remains tied to the user's email.
    key = f'qr-card-magic:{card_id}:{user.pk}'
    try:
        if cache.add(key, True, timeout=300):
            sender_mail_connect(
                user.email,
                next_url=signing.dumps(f'/qr/{card_id}/'),
                template='emails/qr_connexion.html',
            )
    except Exception:
        logger.exception('QR sign-in email dispatch failed')


def _link_card(user, card_id):
    api = FedowAPI()
    wallet, created = api.wallet.get_or_create_wallet(user)
    if not created:
        existing = api.wallet.retrieve_by_signature(user)
        if existing.validated_data.get('has_user_card'):
            return False
    card = api.NFCcard.linkwallet_cardqrcode(user=user, qrcode_uuid=card_id)
    if not card:
        return False
    number = card.get('number_printed')
    if number:
        for membership in Membership.objects.filter(user__isnull=True, card_number=number):
            membership.user = user
            membership.first_name = user.first_name
            membership.last_name = user.last_name
            membership.save(update_fields=['user', 'first_name', 'last_name'])
    return True


@require_GET
def qr_card_landing(request, pk):
    try:
        card, canonical = _card(request, pk)
    except Http404:
        raise
    except Exception:
        logger.exception('QR card lookup failed')
        raise Http404("Carte indisponible")

    if request.get_host().split(':')[0].lower() != canonical.lower():
        return HttpResponseRedirect(f'https://{canonical}/qr/{pk}/')

    if card.get('is_wallet_ephemere'):
        if request.user.is_authenticated:
            try:
                if _link_card(request.user, pk):
                    return HttpResponseRedirect(f'/qr/{pk}/')
            except Exception:
                logger.exception('QR card link failed')
            messages.error(request, _("Cette carte ne peut pas être liée à votre compte."))
            return HttpResponseRedirect('/my_account/')
        return render(request, 'reunion/views/register.html', _context(request, pk))

    try:
        owner = Wallet.objects.get(uuid=card['wallet_uuid']).user
    except (KeyError, Wallet.DoesNotExist, TibilletUser.DoesNotExist):
        raise Http404("Propriétaire introuvable")

    if request.user.is_authenticated:
        if request.user.pk != owner.pk:
            return HttpResponseForbidden(_("Cette carte est liée à un autre compte."))
        context = _context(request, pk)
        context['show_refill_button'] = Configuration.get_solo().show_refill_button
        return render(request, 'reunion/views/qr_landing.html', context)

    _send_magic_link(owner, pk)
    return render(request, 'reunion/views/qr_check_email.html', _context(request, pk))


def qr_card_link(request):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    validator = LinkQrCodeValidator(data=request.POST)
    if not validator.is_valid():
        messages.error(request, _("Vérifiez l'adresse email, sa confirmation et les conditions d'utilisation."))
        return HttpResponseClientRedirect('/')

    card_id = validator.validated_data['qrcode_uuid']
    try:
        card, canonical = _card(request, card_id)
    except Http404:
        messages.error(request, _("Cette carte n'est pas reconnue."))
        return HttpResponseClientRedirect('/')
    except Exception:
        logger.exception('QR card lookup failed')
        messages.error(request, _("Carte indisponible, veuillez réessayer."))
        return HttpResponseClientRedirect('/')
    if request.get_host().split(':')[0].lower() != canonical.lower():
        return HttpResponseClientRedirect(f'https://{canonical}/qr/{card_id}/')
    if not card.get('is_wallet_ephemere'):
        return HttpResponseClientRedirect(f'/qr/{card_id}/')

    if request.user.is_authenticated:
        return HttpResponseClientRedirect(f'/qr/{card_id}/')

    email = validator.validated_data['email'].strip().lower()
    try:
        user, created = get_or_create_user(
            email=email, send_mail=False, return_created=True,
        )
        if not user:
            raise ValueError('Invalid email')
        if not created:
            # A known account must prove control of its email before linking
            # the new card. The signed return URL completes linking on GET.
            _send_magic_link(user, card_id)
            return HttpResponseClientRedirect(f'/qr/check-email/{card_id}/')

        user.first_name = validator.validated_data.get('firstname', '')
        user.last_name = validator.validated_data.get('lastname', '')
        user.accept_newsletter = bool(validator.validated_data.get('newsletter'))
        user.save(update_fields=['first_name', 'last_name', 'accept_newsletter'])
        if not _link_card(user, card_id):
            messages.error(request, _("La liaison de la carte a échoué. Veuillez réessayer."))
            return HttpResponseClientRedirect(f'/qr/{card_id}/')
        # Only a newly created account can enter immediately. Email remains
        # unverified until the confirmation mail is opened.
        user.is_active = True
        user.save(update_fields=['is_active'])
        login(request, user)
        _send_magic_link(user, card_id)
        return HttpResponseClientRedirect(f'/qr/{card_id}/')
    except Exception:
        logger.exception('QR card registration failed')
        messages.error(request, _("La liaison de la carte a échoué. Veuillez réessayer."))
        return HttpResponseClientRedirect(f'/qr/{card_id}/')


@require_GET
def qr_check_email(request, pk):
    return render(request, 'reunion/views/qr_check_email.html', _context(request, pk))
